version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  evaluation_application:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db
